# Basic markdownlint config: friendly and simple
# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

# Relax line length; allow long code blocks and tables
MD013:
  line_length: 120
  code_blocks: false
  tables: false

# Allow first heading to be h1
MD041: false

# Allow inline HTML (for simple badges/iframes if needed)
MD033: false
