http:
  middlewares:
    webhook-ratelimit:
      rateLimit:
        average: 50
        burst: 100
    redirect-to-www:
      redirectRegex:
        regex: ^https?://example\.com(.*)
        replacement: https://www.example.com$1
        permanent: true
    oauth2-forwardauth:
      forwardAuth:
        address: "http://auth:4180/oauth2/auth"
        trustForwardHeader: true
        authResponseHeaders:
          - X-Auth-Request-User
          - X-Auth-Request-Email
          - X-Auth-Request-Preferred-Username
    oauth2-errors:
      errors:
        status:
          - "401-403"
        service: auth@docker
        query: /oauth2/start?rd=https://www.example.com/auth/complete
    tenant-access-check:
      forwardAuth:
        address: "http://provisioner:8080/access/check"
        trustForwardHeader: true
